files:
  - source: /content/en/**/*.*
    translation: /content/%two_letters_code%/**/%original_file_name%
    content_segmentation: 0
    languages_mapping:
      two_letters_code:
        pt-BR: pt-br
  - source: /i18n/en.toml
    translation: /i18n/%two_letters_code%.toml
    dest: /i18n/en.ini
    type: ini
    languages_mapping:
      two_letters_code:
        pt-BR: pt-br
